### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by man4toman**

### CODE REVIEW

**Comment by JulieKuehl** [comment]
Same issue about removing all the links to the `make.wordpress.org` site for lesson plans. Could you please use links to the GitHub repos instead?

**Comment by man4toman** [comment]
Sure, I'll create new PR.

**Comment by man4toman** [comment]
Hi @JulieKuehl 
Would you please check the update?

**Comment by JulieKuehl** [comment]
Thank you for your contribution! Your pull request has been merged.

Sorry for the delay in getting this merged.

**Pull request merged**
